version: '3.8'

services:
  backend:
    build:
      context: ./path/to/nestjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./path/to/reactjs
      dockerfile: Dockerfile
    ports:
      - "3001:3000"